### ISSUE TITLE
Naming the hostnames

### ISSUE THREAD

**Issue by hrb1989** [cyface/docker-saltstack#1]
Hello!

It was wonderful using your docker compose, I feel, we need start naming the container (I mean hostname of the minion as minion1, minion2, master), so that the results will be pretty good!!

**Comment by cyface** [comment]
Hi! The containers get automatically named by Docker to be the names in the docker-compose.yml file - `salt-master` and `docker-saltstack_salt-minion_1` and `docker-saltstack_salt-minion_2`.  I added a better explanation of this to the Medium article and the README just now, so I hope that helps you!

Let me know if there is an approach that would be more useful to you!

**Comment by louwers** [comment]
For me the names are 7061862a922d and cd822588b170
